### ISSUE TITLE
RGB‐NIR Image Enhancement by Fusing Bilateral and Weighted Least Squares Filters

### ISSUE THREAD

**Issue by excllent123** [vivoutlaw/vivoutlaw.github.io#1]
Hi  :
whether  the code of this paper will be release?

**Comment by vivoutlaw** [comment]
I still need to clean the codes, drop me an email after 15th Nov for the same. I'll take a look at it then.

**Comment by excllent123** [comment]
Thanks!

**Comment by vivoutlaw** [comment]
@excllent123 : The proposed fusion codes are now available.

**Comment by gachiemchiep** [comment]
@vivoutlaw  Hello. Where is the link to your code ?
